### ISSUE TITLE
How is the caching / proxying working?

### ISSUE THREAD

**Issue by Thorbijoern** [devpi/devpi#440]
I didn't found any information about this in the documentation.
I know that devpi does not mirror the whole pypi, it is only caching packages after they were first requested.
But what happens on the first request? Does devpi mirror the package first and then serves it to pip, does it mirror and serve the package simultaneously or does it redirect or act as a transparent proxy?

**Comment by fschulze** [comment]
When pip requests the simple index ``devpi-server`` checks if it has current data, if not it looks at PyPI and downloads the simple page for the project. When a file is requested, it is served directly when it's already downloaded, otherwise it is streamed to the client and stored when finished. So it acts as a kind of proxy.

**Comment by ntravis** [comment]
@fschulze this isn't easy to prove out, but my travis-ci build history would disagree that the streaming is occurring. A pattern I've seen regularly is:
- update is released to a third party package
- our monitoring tool for automatic updates creates PRs across several repos
- the updates fail because devpi indicates it doesn't have a matching version to the request
- I check devpi and see it in there and restart builds -> they install correctly this time

Is there some debugging I can provide that will help show this?

**Comment by fschulze** [comment]
@ntravis in this case it's more likely that the simple page cache is to blame. By default it's caching for 30 minutes. You can adjust the cache with the ``--mirror-cache-expiry`` option, but that puts more stress on PyPI and makes devpi slower to respond. Since you already do monitoring and trigger a build from that, you have two other possibilities:

- Use devpi clients "refresh" command
- Trigger a POST on the URL devpi client uses

For simple pages that include PyPI there is a "Refresh PyPI links" button at the top. You can inspect it to see what needs to be done.

The streaming is only done when the file is found and actually downloaded to avoid timeouts for bigger packages on too slow connections (pip has a 60s timeout I think).

**Comment by ntravis** [comment]
Ah, okay. Thanks for the thorough explanation. I'll have to see what I can do with @jayfk to try to trigger a refresh so this happens automatically.

**Comment by jayfk** [comment]
Wouldn't it make sense to bust the cache automatically if there's a release requested that's newer than the current meta data?

Something along the lines of:

```
if requested_release not in releases and requested_release > latest_release:
    bust_the_cache()
```

I have to admit that I don't know very much about devpi internals, is something like that possible? I'd be happy to submit a PR if someone could point me in the right direction (and if this is a feature you'd consider useful).

**Comment by fschulze** [comment]
When pip looks at the simple page it doesn't tell us about the version it's looking for, it just downloads what is there, sees the version pin doesn't match and fails.

**Comment by jayfk** [comment]
All right, that makes sense. Thanks!

**Comment by fschulze** [comment]
Looks resolved. Feel free to reopen if there is more to this.
