### ISSUE TITLE
whitelisting features not working?

### ISSUE THREAD

**Issue by Thorbijoern** [devpi/devpi#441]
I know two whitelisting features, `pypi_whitelist` and `mirror_whitelist` but I dont understand how both of them work and what they really do and the documentation is also very unclear about that.
I read in Issue #198 that they do something different and in the comments in the same Issue was a link to a draft on a mailing list and there was a filtering feature mentioned, but i found no evidence of some filtering you could configure for an index in my tests.
I've tested poth, `pypi_whitelist` and `mirror _whitelist` but I could'nt get them working. I dont know if i used them properly because the documentation does'nt say much about them.

I used devpi with devpi-web, -server and client installed in an virtual environment.

**Comment by danielpanteleit** [comment]
This is how I understand the whitelists. It would be nice if someone could confirm that this is correct.

Assuming you have the indexes root/pypi and user/private with user/private having root/pypi as parent index. Now you upload the package `mypackage` with version 1.0 to user/private. At some point someone publishes a different (or malicious) `mypackage` with version 2.0 to pypi. Without the whitelist you will still get your `mypackage` with version 1.0. If you add the package to `mirror_whitelist` you would get the pypi version of `mypackage` with version 2.0. In general this is not what you want so this is the default behaviour.

This can be useful, though, if you upload a different package type (like a bdist version of a sdist-only package) or upload a version with a fix that is already in the SCM but not on pypi yet.

`pypyi_whitelist` was renamed to `mirror_whitelist` because the concept is not limited to pypi anymore but works with any mirror site. For compatibility reasons this option is still around.

For packages that were not uploaded to your index the whitelist is irrelevant. Those packages will always be loaded from the mirror. A whitelist that would prevent this was proposed in #198.

**Comment by fschulze** [comment]
@danielpanteleit yes, that is how whitelists work

**Comment by Thorbijoern** [comment]
I think the documentation of this feature might be a bit confusing, it could explain a little bit more. I thought this feature has another function, but i'm wrong, thanks for the clarification.

**Comment by fschulze** [comment]
@Thorbijoern would be great, if you could make a PR or suggestions to improve the docs.
