### ISSUE TITLE
push to pypi doesnt include metadata, casues broken pytest metadata on pypy

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [devpi/devpi#480]
followup to pytest-dev/pytest#2966

the pytest release that was pushed by devpi doesnt propperly propagate the requires_python metadata to pypi

**Comment by fschulze** [comment]
I looked at the ticket, but I'm not sure which metadata we should add on push and where to get it. Does only the wheel have that metadata? Is there a spec for the metadata, or do we have to look at what twine does? Can we make it future proof somehow if additional metadata is required?

BTW, I'm maintaining devpi.net mostly, so when an update is needed there, ping me instead of hpk.

**Comment by RonnyPfannschmidt** [comment]
@fschulze the metadata in question we need passed along for pytest is `Requires-Python` im not sure what/how devpi handles it - i would like to propose to just use twine to avoid reimplementation of the logic
