### ISSUE TITLE
Add ability for "--with-docs --dry-run" to generate docs UNZIPPED

### ISSUE THREAD

**Issue by nmz787** [devpi/devpi#515]
I have tried searching online a few times now for the devpi command-line options, but have not been successful.
Maybe this link is misleading and not the same devpi?
 (https://devpi.net/docs/devpi/devpi/stable/%2Bd/index.html)

Essentially I would like to run `devpi upload --with-docs --dry-run` without the docs being zipped up. This is because the whole point of me running dry-run is to check the docs to see if they generated properly. So as-is, I have to run `devpi`, then unzip the docs file, then I can open `index.HTML` and check things. Inevitably I have to perform this several times for each release I'm doing, and it is really annoying even though it only adds a few seconds of typing and clicking. It's annoying enough that I wish `devpi` already had this ability (but who knows, I can't find the cmd-line args in the docs). Alternatively if you don't want to add this ability, I guess I'll just write a local wrapper that automatically unzips all `ZIP` files in the `dist` folder which is created by `devpi`.

**Comment by fschulze** [comment]
The link is correct, the exact page is:
https://devpi.net/docs/devpi/devpi/stable/+d/userman/devpi_commands.html#upload

``devpi upload`` uses build_sphinx, so you could just use that directly. The following links show how it's setup, which you most likely know, otherwise devpi couldn't create the docs, but it also shows how to call the command directly. The ``build`` dir should contain the unpacked docs.

https://pythonhosted.org/an_example_pypi_project/buildanduploadsphinx.html#using-sphinx-pypi-upload
http://www.sphinx-doc.org/en/stable/setuptools.html
https://pypi.org/project/Sphinx-PyPI-upload-2/

**Comment by nmz787** [comment]
Thanks @fschulze ! `setup.py build_sphinx` does the trick!

Not sure why Google doesn't rank the command-line documentation link in the top search results (for example `devpi "--with-docs"`)... but hopefully this issue will draw more attention to their algorithm.
