### ISSUE TITLE
Get UpstreamError while changing index value

### ISSUE THREAD

**Issue by yorodm** [devpi/devpi#556]
I'm trying to change an existing index mirror_url since the old one stopped working and I need to keep the downloaded packages. Is there a viable solution that doesn't imply creating a new index?

**Comment by fschulze** [comment]
This is a bug that is hard to fix at the moment. The issue is that devpi-client currently first fetches the existing json which includes the project names, updates that json and then sends it back.

But here is a workaround:

Create a file (lets name it ``patch.json``) with at least this content:
```
{"type": "mirror", "mirror_url": "NEW_URL"}
```

Select the correct server with ``devpi use``, login with the user that has permission to change the index and run this:
``devpi patchjson /USER/INDEX patch.json``

Replace NEW_URL, USER and INDEX with the respective values for your index.

**Comment by fschulze** [comment]
The new ``+=`` and ``-=`` operators for setting index options (devpi-server 4.8.1) should also fix this.
