### ISSUE TITLE
Refresh button on non-simple package page?

### ISSUE THREAD

**Issue by rcoup** [devpi/devpi#601]
While eg. https://mydevpi.example.net/root/pypi/+simple/botocore has a refresh button to reset the package state from upstream PyPi, the UI page you get to by searching for the package (eg. https://mydevpi.example.net/root/pypi/botocore) doesn't.

1. The UI page should have a refresh button. It's a manual intervention, might as well make it as easy as possible to do.
2. Since the simple view has [code to hide the refresh form from pip](https://github.com/devpi/devpi/blob/master/server/devpi_server/views.py#L443-L451) user-agents anyway, could it just _move_ to the UI page?

**Comment by fschulze** [comment]
The reason it's on the simple page is because that page is in devpi-server. The UI is in devpi-web. So I have no intention in moving it.

The "Simple index" link is easily reachable, so I don't think it's that much of a stretch to use it to get to the button.

I'm more concerned about the reason you need the refresh button in such a prominent place. Do you need it that often? Do you know about the ``--mirror-cache-expiry`` option? Could/should we look into further ways to prevent the need of the refresh button?

**Comment by rcoup** [comment]
> The "Simple index" link is easily reachable, so I don't think it's that much of a stretch to use it to get to the button.

It's not linked from the package page... you need to click through to a version, then click "Simple index". 

> The UI is in devpi-web. So I have no intention in moving it.

Ah, of course. A button could be added that posts to the same simple-refresh url though? Wouldn't redirect back properly, but gets the job done easily.

> Do you need it that often?

Only occasionally, but that's why I think it's hard to find :) Usually we run into it when some packages release in quick succession and the pypi cache (30 minutes) hasn't expired in the right order. AWS' boto* packages are a particular example since they seem to push new releases 5-10 times a week.

**Comment by fschulze** [comment]
I think we should add some more info the the package page then and look into maybe linking to the current stable version from search results.

Now that I know this is about the package page and not the version page I'm also leaning towards adding a button there, because one can see the results on that page as well unlike the version page where the button would not cause any effect.

**Comment by fschulze** [comment]
> > The "Simple index" link is easily reachable, so I don't think it's that much of a stretch to use it to get to the button.
> 
> It's not linked from the package page... you need to click through to a version, then click "Simple index".

I added the link for upcoming devpi-web 4.1.0.

Probably will add the button as well.
