### ISSUE TITLE
--recreate-search-index for a replica?

### ISSUE THREAD

**Issue by sdwilliams61** [devpi/devpi#620]
Hello all,
[Apologies if I've missed a pre-existing answer to my question]

We've got v4.6.0  devpi master and replica server,  devpi-web is installed.  The system has been operational for several months w/SQLite files at about 15Gb.   *Thank you!*

Unfortunately, I need to rebuild the .indices directory on the replica (only).  I have tried it without much luck, meaning, I watched the subdirectories under .indices and saw no changes over a long period.   

 I notice that the docs for --recreate-search-index don't specify what role a server is. Does it matter?

Is there any way to rebuild the search index wholly with the (offline) replica data?

Any general issues to consider when rebuilding a search index in this arrangement?  

BTW, I like the direction this is going: https://github.com/devpi/devpi/issues/566

Thanks again,
Scott

**Comment by fschulze** [comment]
The master should be taken offline to make a copy of ``.indices`` and the replica should be at the same serial as the master. Otherwise there could be missing or too much data in the search index.

``--recreate-search-index`` will be pretty slow. One big factor are all the project names from ``root/pypi``. An empty devpi-server with current ``root/pypi`` takes almost an hour to index on my laptop. If you additionally have many projects with uploaded documentation, that will add to the time to index. Memory usage could also be pretty high. These are all reasons for the #566 proposal. Everything is also done in one commit, which is why you don't see any change on the filesystem.

**Comment by fschulze** [comment]
The original issue seems to be solved.
