### ISSUE TITLE
Aligning supported Python versions

### ISSUE THREAD

**Issue by 00willo** [devpi/devpi#694]
There's an existing PR (https://github.com/devpi/devpi-ldap/pull/48) to remove python 3.4 from the ldap auth plugin.

I did a quick look at what's around in various setup.py, tox.ini and documentation. I have a couple of quick questions.

- Is python 3.4 still determined to be "officially" supported by devpi?
- Is python 3.7 deemed supported, as I noticed that 3.7 is missing from `setup.py` as a version, as well as not being explicitly tested via `tox.ini` and `.travis.yml`
- With 2.7 reaching EOL at the end of the year, would that mean that devpi would no longer support it, or would the continued use and support by various distros impact this?
- Where would be good to document the generalised statement on the current position of the project on what are the supported versions? 

I can raise a PR to align all the things once the answers to these are determined.  Maybe 

I'm working on this as the reference for the current python versions - https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by fschulze** [comment]
See https://github.com/devpi/devpi/issues/638#issuecomment-491418019

To summarize again:

devpi-client will support 2.7, 3.4 to current for as long as feasible. That means as long as the necessary workarounds to test it with Travis and AppVeyor are small enough (version pins etc) we will support it. We won't compile Python from source with custom patches or things like that (jury is out for compiling python at all). The decision on what is small enough is driven by funding via support contracts.

devpi-server 5.0.0 is the last major version to support 2.7, it will support 3.4 to current like devpi-client, but the threshold for dropping 3.4 is quite a bit lower. I think people who want to install devpi-server can also install relatively current Python versions.

For Travis we test 2.7, 3.4 and 3.7. I skip 3.5 and 3.6, because I don't expect them to break if the older and newer ones don't. Also the test runs are long enough as they are. Also pypy is somewhere in the middle.

If the setup.py files are missing something, then please provide a fix.

The tox.ini files should be in sync with Travis, though there might be some extra environments which should stay. If you are unsure, keep them as is.

**Comment by 00willo** [comment]
Thanks, I missed that previous issue. Yeah, in https://github.com/devpi/devpi/issues/638#issuecomment-491418019, Debian buster (current stable) is shipping with 3.7.

I take it you'd probably like to just align the testing and support for 3.4 for devpi-server in line with devpi-client for the moment, correct?

I'll update the setup.py files.
