### ISSUE TITLE
Can I duplicate or rename an index?

### ISSUE THREAD

**Issue by ghicks-rmn** [devpi/devpi#742]
Currently running devpi 4.1. 

When I originally set it up we created a single index (we'll call it `local`) that had `root/pypi` as a base, and put our custom packages in it. 

Now I want to separate our custom packages out into their own index (with no base - call this one `internal`), but do so without disrupting builds and users that expect the current index to have PyPI packages. So, my end goal is to have `internal` with custom packages and no base, and `local` with both `internal` and `root/pypi` as bases.

I can think of a couple ways to do this relatively transparently, but they all involve duplicating an index under another name, copying an index package-by-package, or renaming an index. I can't seem to find an easy way to do any of these. Can someone help me figure one of these out, or possibly suggest another option?

**Comment by fschulze** [comment]
There is currently no way to rename an index and due to the internal use of a key value store this would also be a rather complicated operation.

I can't think of a super simple solution either, but you could write a small script to do it.
You could use the json output of `devpi getjson` to iterate over the projects and releases and use `devpi push` to copy the releases into the new index.

I hope this helps.

**Comment by fschulze** [comment]
No reply in more than 3 months. Feel free to reopen this issue if it isn't solved yet.
