### ISSUE TITLE
pypi_whitelist being present causes general whitelisting and other problems

### ISSUE THREAD

**Issue by con-f-use** [devpi/devpi#781]
So, I had migrated my devpi-server a while back from 4.8.x to 5.4.0. 

It used to have `mirror_whitelist` and the obsoleted `pypi_whitlist` set, e.g. it was present in the output of `devpi index root/devel`, both empty, so nothing whitelisted. I just now realized that despite nothing in the whitelist a package from the parent index (pypi.org) got installed although a (lower) version of a package of the same name was on `root/devel`.

I could correct that behavior by simply running `devpi index root/devel pypi_whitelist-=` . That leads me to belief something in the migration process is amiss.

I understand `pypi_whitelist` was supposed to be removed and ignored since devpi-server 5.3.0.

In trying to reproduce this issue, I also noticed that when running `devpi root/devel mirror_whitelist=-` by accident, weird things happen:

```
$ devpi root/devel | grep mirror_
  mirror_whitelist=

$ devpi root/devel mirror_whitelist=- &>/dev/null  # introduces glitch

$ devpi index root/devel 'mirror_whitelist=[testpkg,testpkg2]' | grep mirror_             
/root/devel mirror_whitelist=[testpkg,testpkg2]
  mirror_whitelist=-testpkg,testpkg2-

$ devpi index root/devel 'mirror_whitelist=[]' | grep mirror_                             
/root/devel mirror_whitelist=[]
  mirror_whitelist=-
```

I.e. the unusual hyphen (`-`) cannot be removed once glitched into existence.

**Comment by fschulze** [comment]
I couldn't find any issues when ``pypi_whitelist`` is still present. The blocking of releases from root/pypi still works for me in that case. Are you sure this wasn't caused by something else?

Your fix to remove ``pypi_whitelist`` was correct.

For me trying to remove ``mirror_whitelist`` the same way returns an error and it should do so since devpi-server 5.1.0:
```
400 Bad Request: Default values can't be removed.
```

The remaining issues you have are all because of the square brackets. On the command line they aren't used and thus interpreted as part of the package name and normalized, which turns the square brackets into dashes. If you just leave out the square brackets, everything should work as expected.
