### ISSUE TITLE
Devpi-web vulnerabilities on JavaScript libraries

### ISSUE THREAD

**Issue by sirote** [devpi/devpi#823]
There are vulnerabilities on the following JS used by devpi-web. Is there a plan to update them?
 
[CVE-2016-4055](https://nvd.nist.gov/vuln/detail/CVE-2016-4055): moment-2.8.2.min.js
[CVE-2015-9251](https://nvd.nist.gov/vuln/detail/CVE-2015-9251): jquery-1.11.1.min.js

**Comment by fschulze** [comment]
Neither of these vulnerabilities apply to devpi-web (or devpi-server).

The ``moment`` one can't be exploited, because the string is controlled by the server, not user modifiable content. If someone is able to modify data affected by this, then you have bigger problems elsewhere.

The ``jquery`` one doesn't apply, because we don't use it for ajax calls.

I will look into updating them anyway, so I'll leave this ticket open as a reminder.

**Comment by xrmzju** [comment]
is there any update here?

**Comment by fschulze** [comment]
The next major version will remove moment.js and update jQuery. As already stated, this isn't anything urgent as the vulnerable parts aren't used.

**Comment by fschulze** [comment]
Fixed with devpi-web 4.2.0.
