### ISSUE TITLE
Dependency Confusion vulnerability

### ISSUE THREAD

**Issue by agentram** [devpi/devpi#830]
Hello,

This [vulnerability](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610) isn't directly related to devpi but it would be nice to hear your recommendations on it. 

1. Could you explain how devpi will download a package if it exists in the local index and in PyPi with the same name, and the version in PyPi will be higher than the local version?
2. Is it possible to disable downloading from PyPi if a package with the same name exists in the local index?

**Comment by Pierre-Sassoulas** [comment]
I also just read the documentation and did not find the answer. It would be nice to be able to explicitly configure the server so that if a package exists on an inherited index even with a higher version than the server version is used.

**Comment by fschulze** [comment]
This is default behaviour if the ``mirror_whitelist`` option of a private index is kept empty or only set to names of public packages. Only if ``mirror_whitelist`` is set to ``*`` or includes private package names will it look at releases from pypi.org. Also see original implementation introduced via #103. Please note that originally the option was called ``pypi_whitelist``. I'm considering renaming it again to ``trust_mirror_releases_for`` to make the naming clearer.

**Comment by agentram** [comment]
Thank you. Checked. It is empty by default.

**Comment by manselmi** [comment]
Hello @fschulze,

To help protect against "dependency confusion", it is possible to do the following?

Suppose I have an index `foo` with two base indices: `pypi` and `corporate`, where `pypi` points to PyPI and `corp` points to a private Artifactory index containing only private packages from my employer.  All packages in the `corp` index have their names prefixed by, say, `prefix` to avoid name collisions with PyPI packages.  (I run devpi locally to cache any package downloaded through the `corp` index, to simplify offline development.)

Is it possible to exclude _any_ package whose name begins with `prefix` from the `pypi` index?  For example, I'm making these up, but something like `deny_regex: r'^prefix'` or `allow_regex: r'^(?!prefix)'`.  This way, if pip is configured to use the `foo` index and I run `pip install <private_pkg>` for any private package I'll be guaranteed that any package I get will come from the `corp` index, because all private package names begin with `prefix`.

This way, I would not need to maintain an allowlist or blocklist targeting exact package names that, in my case, would frequently require updating.

**Comment by fschulze** [comment]
@manselmi If you keep ``mirror_whitelist`` empty as is the default, all your packages uploaded to ``corporate`` are protected by default if you use the ``corporate`` index or have it in your index ``bases``. Only if you would use ``root/pypi`` directly could you be vulnerable.

In other words, if you use default settings you are protected without any further settings.

**Comment by manselmi** [comment]
> @manselmi If you keep `mirror_whitelist` empty as is the default, all your packages uploaded to `corporate` are protected by default if you use the `corporate` index or have it in your index `bases`. Only if you would use `root/pypi` directly could you be vulnerable.
> 
> In other words, if you use default settings you are protected without any further settings.

Hi @fschulze,

Thanks for the reply but I think there may be a misunderstanding. I just tested this by uploading an older version of `devpi-client` (5.2.1)  to the `corp` Artifactory index, clearing pip’s cache, pointing pip to the `foo` index then running `pip download --no-deps devpi-client`. I got the latest version (5.2.2) via the `pypi` index instead of the older version from the `corp` index.

This is what I expected would happen, since the `foo` index has the `pypi` and `corp` indices as bases, and I wouldn’t expect one base to be treated differently from the other without additional configuration.

In this contrived example, what I would be looking for is a way to apply an allowlist or denylist to the `pypi` index to block any package whose name begins with `devpi`. In reality the prefix would be my corporate namespace. There are a large number of packages to block, all following the same naming convention, hence the request to block by regex instead of by every individual package.

What would also solve the problem quite handily would be if a mirror index could have another mirror index as a base. That way I could have `pypi` be a base of `corp`, which I believe would mean that a package in `corp` would shadow a corresponding package in `pypi`, which is exactly what I would like.

**Comment by fschulze** [comment]
@manselmi Is is the ``mirror_whitelist`` setting of the ``foo`` index empty?

If ``corp`` has ``root/pypi`` in bases (and nothing else), then ``foo`` only needs ``corp`` in bases and can leave ``root/pypi`` out.

I have to recheck, but I think as long as ``mirror_whitelist`` is empty in all involved indexes, then it should also work if ``foo`` has both ``root/pypi`` and ``corp`` as bases. I need to test it to be sure though.

**Comment by manselmi** [comment]
> @manselmi Is is the `mirror_whitelist` setting of the `foo` index empty?
> 
> If `corp` has `root/pypi` in bases (and nothing else), then `foo` only needs `corp` in bases and can leave `root/pypi` out.
> 
> I have to recheck, but I think as long as `mirror_whitelist` is empty in all involved indexes, then it should also work if `foo` has both `root/pypi` and `corp` as bases. I need to test it to be sure though.

Yes, I believe `mirror_whitelist` is not set. I know I did not explicitly set it but this output gives the impression it is set to an empty value:

```
# devpi index root/foo

http://localhost:3141/root/foo:
  type=stage
  bases=root/pypi,root/corp
  volatile=True
  acl_upload=root
  acl_toxresult_upload=:ANONYMOUS:
  mirror_whitelist=
  title=Foo: personal index
```
`mirror_whitelist` would not be applicable to `corp` or `pypi` because those are mirror indices, right?

**Comment by fschulze** [comment]
Ah, I think I misunderstood you. Do I understand correctly that ``root/corp`` is actually a mirror and not a regular index? If so, then this whole concept falls apart for you. Does ``root/corp`` need to be a mirror? Why isn't devpi itself used for your private packages?

You might have to look into [``devpi-contrained``](https://pypi.org/project/devpi-constrained/). Currently I'm not sure if you would be able to solve your issue with that though. It might work if you add a constrained index which has ``root/pypi`` as bases and blocks packages with the prefix as you proposed and all other indexes inherit from the constrained index instead of ``root/pypi`` directly.

**Comment by manselmi** [comment]
> Ah, I think I misunderstood you. Do I understand correctly that `root/corp` is actually a mirror and not a regular index?

Yes, that’s right. As mentioned earlier, I’m running devpi locally in this way to take advantage of caching to simplify offline development. I don’t store any packages in the `foo` index; it’s just there as a way to combine the other two mirror indices.

> Does `root/corp` need to be a mirror? Why isn't devpi itself used for your private packages?

Yes, I would like for it to be a mirror because these are not _my_ packages, but my company’s packages. This is where all internal devs publish packages so I would like a mirror index to be the source of internal packages in my local devpi setup.

> You might have to look into devpi-contrained. Currently I'm not sure if you would be able to solve your issue with that though. It might work if you add a constrained index which has root/pypi as bases and blocks packages with the prefix as you proposed and all other indexes inherit from the constrained index instead of root/pypi directly.

Thanks! I looked at the documentation for `devpi-constrained` but it wasn’t clear to me if I can block all packages with some prefix, or if I have to block each package individually (there are hundreds). Is it possible to block all packages with some prefix?

**Comment by fschulze** [comment]
The ``devpi-constrained`` plugin evolved quite a bit until it was released. In its current form it doesn't solve your usecase. You could use the same hooks it uses to do what you need. This is out of scope for default ``devpi-server`` and the goals of ``devpi-constrained`` (filter with as little performance impact as possible). See contact information at https://merlinux.eu/ if you need commercial support for this.

**Comment by fschulze** [comment]
The contact for commercial support has changed to ``mail (at) pyfidelity.com``. Since there was no follow up in several months I will close this ticket.
