### ISSUE TITLE
Documentation packages slow to load

### ISSUE THREAD

**Issue by rbracewell** [devpi/devpi#893]
Running the following versions
devpi-postgresql-3.0.0
devpi-server-6.5.0
devpi-web-4.0.8

Noticing that documentation associated with uploaded packages is extremely slow to load. For example, a 1MB documentation package makes 21 requests when using Chrome developer tools and takes around 16.5 seconds before complete.

Any advice on how to debug this further?

**Comment by fschulze** [comment]
On first request the documentation is unpacked from the zip file and stored on the filesystem. On further requests it is served directly from the filesystem by devpi-server. Is only the first access that slow, or all subsequent requests as well? You can run devpi-server with ``--debug`` to see more output in the log, maybe something in there will tell you more. Otherwise check the filesystem access to see if the slowdown is coming from there.

**Comment by fschulze** [comment]
No followup in more than 3 months. Feel free to reopen with new information if the problem persists.
