### ISSUE TITLE
Getting warning while pointing devpi client

### ISSUE THREAD

**Issue by rakeshkarkare** [devpi/devpi#915]
Hi Team, 

I am getting below warning and unable to proceed, could you please help on this ?

I am using ❯ devpi-server --version
6.0.0

```
❯ devpi use https://qa-automation
WARN: devpi-client-6.0.0 got an unversioned reply, assuming API-VERSION 2 (as implemented by devpi-server-2.0)
GET https://qa-automation/+api
404 Not Found
```

My Machine Mac OS Monterey Version 12.4

**Comment by fschulze** [comment]
It looks like the server is not available at the URL you are trying to reach. You should try to open the URL in a browser to see what content is served instead and then check your configuration/assumptions on the server. Since you seem to be using ``https`` you must have a proxy server in front of ``devpi-server`` and it might not be configured correctly. The webserver library used by devpi-server does not support ``https`` by itself.

**Comment by fschulze** [comment]
See if this issue regarding ``$scheme`` and ``https`` in the nginx config matches your problem:
https://github.com/devpi/devpi/issues/840#issuecomment-1011289385

**Comment by fschulze** [comment]
Have you been able to get this to work?

**Comment by fschulze** [comment]
No follow-up for several months. If this is still an issue, feel free to re-open.
