### ISSUE TITLE
Docview is now clamping the height of the iframe that shows the package document to 150px

### ISSUE THREAD

**Issue by luketunmer** [devpi/devpi#970]
A commit back in Nov last year to change the way in which the docview iframe height is calculated seems to have broken the showing of all package documents:

https://github.com/devpi/devpi/commit/cf60c5e7359cb513209b192947d9c06d36b8a247

The docview now clamps the height of the iframe to 150px regardless of what document is shown. Documents with different themes are all affected.

The resize event javascript function that is invoked when the iframe is resized always computes the height of its html contents to be 150px, and then the iframe height is fixed at this size. This tiny view of the document makes it impossible to use the documentation of our python packages.

Firefox and Chrome then have slightly different behaviour in how they show scrollbars.

It would be nice if the iframe could behave more responsively based on the size of the window.

Versions of devpi:

devpi-postgresql-3.0.1
devpi-server-6.8.0
devpi-web-4.2.0

**Comment by fschulze** [comment]
Is https://devpi.net/docs/devpi/devpi/stable/%2Bd/index.html affected for you as well?

**Comment by luketunmer** [comment]
This page shows the full document correctly. Stepping through the javascript shows that the ResizeObserver function gets the size of its entry contentRect correct, whereas at the same point in our devpi server it always returns 150. Have some changes to this js or css been made in the dev2 version of the web plugin?

Thanks for getting back to me so quickly.

**Comment by fschulze** [comment]
I've just updated devpi.net to the released devpi-web 4.2.0 (dev2 was older). Do you have any customizations of the devpi-server theme? If so, you have to make the same change as in the commit: https://github.com/devpi/devpi/commit/cf60c5e7359cb513209b192947d9c06d36b8a247#diff-e86c0b4186a404089ea5abdbc8a9784cba13460d5209d67a2ae7727a67e1d630 I think before that change the height of the iframe was fixed to 150px from the container it is in. Did you try to clear the browser cache (just making sure)?

**Comment by luketunmer** [comment]
No, we don't customize the devpi-server or web packages with anything. In fact the css delivered to the browser (both firefox and chrome debuggers) show the css for the iframe is as expected (i.e. there is no position or margin styles, as indicated by your diff).

Aha - it does appear to be related to the theme: I found a package in our server with a document in it that was different theme, and it rendered okay. The docs that are rendered poorly seem to be our modified read-the-docs and sizzle themes (corporate colours and the like). These themes all render fine on their own, of course.

It's not clear to me yet what is specifically different about these themes that causes the problem when rendered through docview, It might be that both of these themes attempt to pin some divs so they don't scroll (either the title or the contents section). Do you think there could be a conflict there?

Perhaps the best thing to do is if I can change the link for the document shown in the various tables of packages to pull out the document itself - the +doc url rather than the +d url. Is there an easy way to do this, do you know?

Again - thanks for your help.

**Comment by fschulze** [comment]
If you have nginx in front, I would add a URL rewrite.

If there is no nginx in front, then without touching code, you could customize ``common.js`` in a devpi-server theme to rewrite URLs like ``docview.js`` does (look for ``base_url`` and ``baseview_url`` in there) to point to the unwrapped docs.

Otherwise you would have to change ``views.py`` in devpi-web to use other routes for generating the URLs.

**Comment by fschulze** [comment]
If you find any public docs which exhibit this issue, then please let me know with a link, so I can investigate the cause.

**Comment by luketunmer** [comment]
Thanks for you help. I will try one of these solutions to bypass the +d url. Trying to fix the problem in either the devpi js or the various themes we use is beyond my css skills :-).

**Comment by zerocewl** [comment]
@fschulze 

we have the same issue after an update of an older version of devpi.
Any chance to get a fix in `devpi-web`?
The nginx workaround for rewrite `+d` to `+doc` does the job, but feels a bit hacky ;-)

The bug depends on which theme is used. The default sphinx theme works fine, but a custom theme like [furo](https://github.com/pradyunsg/furo) does not display the correct height (instead only shows the content at `150px` height).

**Comment by fschulze** [comment]
Does anyone have a pointer of a public project with the furo theme or another one which exhibits the problem? But thanks for pointing out a theme, if I get the time, I can switch an existing project to it to try and debug the issue.

**Comment by fschulze** [comment]
The problem is, that the theme sets ``html`` and ``body`` to ``height: 100%``, which prevents the calculation of the full content height to work as it will always use the height of the iframe container. I have to overwrite the css properties in the iframe from ``docview.js``. I'm not sure that this will fix all themes.

I also made the content and iframe use all available browser height, as otherwise short documentation content would cut off the left sidebar of the furo theme. It still isn't perfect, as the TOC will get a scroll bar in some cases, but I think that is a choice of the theme that we can't influence. It does the same on small screens when viewed without iframe.

I also fixed layout jumping by setting a stable scrollbar gutter.

Please test this with the development release:
https://m.devpi.net/fschulze/dev/devpi-web/4.2.2.dev0
https://m.devpi.net/fschulze/dev/+f/933/ec74e4331b8cb/devpi_web-4.2.2.dev0-py3-none-any.whl
