### ISSUE TITLE
Support PEP-691: JSON response to the `/simple` API endpoint

### ISSUE THREAD

**Issue by jeffwidman** [devpi/devpi#986]
This ticket tracks adding JSON support for the `/simple` API endpoint, as defined in https://peps.python.org/pep-0691/.

This is related but a different request than this other ticket which appears to be limited in scope to adding support for per-project JSON responses:
* https://github.com/devpi/devpi/issues/801

**Comment by fschulze** [comment]
If I'm not mistaken, that is already implemented since devpi-server 6.6.0:
[- Support `PEP-691 <https://peps.python.org/pep-0691/>`_ conformant fetching for mirrors, and requests with JSON result for installers. Proxy servers should add compression support for the ``application/vnd.pypi.simple.v1+json`` content type (``gzip_types`` for nginx).](https://github.com/devpi/devpi/blob/main/server/CHANGELOG#L108)

**Comment by jeffwidman** [comment]
Oh indeed!

I'd searched issues and PR's for `"691"` and hadn't found any hits, so I'd assumed it wasn't supported.

Is this supported for both `/simple` and `/<project>/` endpoints? 

It's unclear from the changelog description and `git blame` against that part of the changelog doesn't provide any helpful breadcrumbs pointing to the associated commit.

If supported for both, then this should be closed.

**Comment by fschulze** [comment]
Both should be implemented:
[_simple_list_all_json_v1](https://github.com/devpi/devpi/blob/1c2a8e05f936a309727d76ead840e9d5fb0052b1/server/devpi_server/views.py#L782)
[_simple_list_project_json_v1](https://github.com/devpi/devpi/blob/1c2a8e05f936a309727d76ead840e9d5fb0052b1/server/devpi_server/views.py#L674)

**Comment by jeffwidman** [comment]
Awesome!
